feat: Proxy contract registry
sedaprotocol/seda-chain pull request #49
Opened 2023-09-18 18:39 UTC by hacheigriega

## Motivation

## Explanation of Changes

## Testing

Tested in a local environment manually.

## Related PRs and Issues

Closes: Issue #47

2023-09-22 14:12 UTC, Thomasvdam reviewed
I'll be honest: I need to get more familiar with the project before I feel comfortable approving PRs. :D 
It doesn't always look clear to me, but I think that's more so my unfamiliarity with the SDK than any issues with the code.

2023-09-22 15:13 UTC, JeancarloBarrios requested changes
Hey, I think it broke the test. Can you run all the keeper tests? But its because don't have actions to run it for us at the PR level.

2023-09-22 15:32 UTC, hacheigriega commented
@Thomasvdam Thanks for taking the time to go through the code nonetheless.
@JeancarloBarrios I quickly fixed the test with a nil keeper since I wasn't sure how to mock wasm `ContractOpsKeeper`..

2023-09-22 15:33 UTC, hacheigriega commented on x/wasm-storage/keeper/msg_server.go
> +	// }
nope - removed!

2023-09-22 16:39 UTC, gluax approved these changes
So if I'm understanding correctly, this is for being able to update the proxy address in gov? Not instantiating it before the network runs right? But I notice it's admin only(I think)? Don't we want anyone to be able to update the proxy for it to be permissionless? Or did I misunderstand and this for launching the initial proxy contract after we start the network?

CC @mariocao @FranklinWaller

2023-09-22 16:51 UTC, hacheigriega commented
@gluax Yes, you understood correctly. It's not admin-only though (we don't even have the concept of admin on chain). Perhaps the authority check part confused you, but that is just to ensure that the transaction comes from the governance module. You got me wondering how we know governance module signature cannot be forged, though..

2023-09-22 17:53 UTC, JeancarloBarrios commented
> @Thomasvdam Thanks for taking the time to go through the code nonetheless. @JeancarloBarrios I quickly fixed the test with a nil keeper since I wasn't sure how to mock wasm `ContractOpsKeeper`..

I will add this in a separate PR!!

2023-09-22 17:54 UTC, JeancarloBarrios approved these changes

2023-09-25 09:14 UTC, mariocao approved these changes
Thanks for adding the testing steps!

2023-09-25 15:52 UTC, merged